# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Shared Fabric properties
loader_version=0.19.3
mod_loader=fabric

# Mod properties
mod_id=mc-wiki
mod_name=Minecraft Wiki Mod
mod_version=1.0.0
maven_group=io.github.piscescup.mcwiki
archives_base_name=mc-wiki
